// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: connection.proto

package connection

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CompanyService_FollowCompany_FullMethodName            = "/job.CompanyService/FollowCompany"
	CompanyService_UnfollowCompany_FullMethodName          = "/job.CompanyService/UnfollowCompany"
	CompanyService_IsFollowingCompany_FullMethodName       = "/job.CompanyService/IsFollowingCompany"
	CompanyService_GetFollowedCompanies_FullMethodName     = "/job.CompanyService/GetFollowedCompanies"
	CompanyService_CheckFollowRequestExists_FullMethodName = "/job.CompanyService/CheckFollowRequestExists"
)

// CompanyServiceClient is the client API for CompanyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompanyServiceClient interface {
	FollowCompany(ctx context.Context, in *FollowCompanyRequest, opts ...grpc.CallOption) (*FollowCompanyResponse, error)
	UnfollowCompany(ctx context.Context, in *UnfollowCompanyRequest, opts ...grpc.CallOption) (*UnfollowCompanyResponse, error)
	IsFollowingCompany(ctx context.Context, in *IsFollowingCompanyRequest, opts ...grpc.CallOption) (*IsFollowingCompanyResponse, error)
	GetFollowedCompanies(ctx context.Context, in *GetFollowedCompaniesRequest, opts ...grpc.CallOption) (*GetFollowedCompaniesResponse, error)
	CheckFollowRequestExists(ctx context.Context, in *CheckFollowRequestExistsRequest, opts ...grpc.CallOption) (*CheckFollowRequestExistsResponse, error)
}

type companyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCompanyServiceClient(cc grpc.ClientConnInterface) CompanyServiceClient {
	return &companyServiceClient{cc}
}

func (c *companyServiceClient) FollowCompany(ctx context.Context, in *FollowCompanyRequest, opts ...grpc.CallOption) (*FollowCompanyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowCompanyResponse)
	err := c.cc.Invoke(ctx, CompanyService_FollowCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) UnfollowCompany(ctx context.Context, in *UnfollowCompanyRequest, opts ...grpc.CallOption) (*UnfollowCompanyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowCompanyResponse)
	err := c.cc.Invoke(ctx, CompanyService_UnfollowCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) IsFollowingCompany(ctx context.Context, in *IsFollowingCompanyRequest, opts ...grpc.CallOption) (*IsFollowingCompanyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowingCompanyResponse)
	err := c.cc.Invoke(ctx, CompanyService_IsFollowingCompany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) GetFollowedCompanies(ctx context.Context, in *GetFollowedCompaniesRequest, opts ...grpc.CallOption) (*GetFollowedCompaniesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowedCompaniesResponse)
	err := c.cc.Invoke(ctx, CompanyService_GetFollowedCompanies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *companyServiceClient) CheckFollowRequestExists(ctx context.Context, in *CheckFollowRequestExistsRequest, opts ...grpc.CallOption) (*CheckFollowRequestExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowRequestExistsResponse)
	err := c.cc.Invoke(ctx, CompanyService_CheckFollowRequestExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CompanyServiceServer is the server API for CompanyService service.
// All implementations must embed UnimplementedCompanyServiceServer
// for forward compatibility.
type CompanyServiceServer interface {
	FollowCompany(context.Context, *FollowCompanyRequest) (*FollowCompanyResponse, error)
	UnfollowCompany(context.Context, *UnfollowCompanyRequest) (*UnfollowCompanyResponse, error)
	IsFollowingCompany(context.Context, *IsFollowingCompanyRequest) (*IsFollowingCompanyResponse, error)
	GetFollowedCompanies(context.Context, *GetFollowedCompaniesRequest) (*GetFollowedCompaniesResponse, error)
	CheckFollowRequestExists(context.Context, *CheckFollowRequestExistsRequest) (*CheckFollowRequestExistsResponse, error)
	mustEmbedUnimplementedCompanyServiceServer()
}

// UnimplementedCompanyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCompanyServiceServer struct{}

func (UnimplementedCompanyServiceServer) FollowCompany(context.Context, *FollowCompanyRequest) (*FollowCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowCompany not implemented")
}
func (UnimplementedCompanyServiceServer) UnfollowCompany(context.Context, *UnfollowCompanyRequest) (*UnfollowCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowCompany not implemented")
}
func (UnimplementedCompanyServiceServer) IsFollowingCompany(context.Context, *IsFollowingCompanyRequest) (*IsFollowingCompanyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFollowingCompany not implemented")
}
func (UnimplementedCompanyServiceServer) GetFollowedCompanies(context.Context, *GetFollowedCompaniesRequest) (*GetFollowedCompaniesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowedCompanies not implemented")
}
func (UnimplementedCompanyServiceServer) CheckFollowRequestExists(context.Context, *CheckFollowRequestExistsRequest) (*CheckFollowRequestExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFollowRequestExists not implemented")
}
func (UnimplementedCompanyServiceServer) mustEmbedUnimplementedCompanyServiceServer() {}
func (UnimplementedCompanyServiceServer) testEmbeddedByValue()                        {}

// UnsafeCompanyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompanyServiceServer will
// result in compilation errors.
type UnsafeCompanyServiceServer interface {
	mustEmbedUnimplementedCompanyServiceServer()
}

func RegisterCompanyServiceServer(s grpc.ServiceRegistrar, srv CompanyServiceServer) {
	// If the following call pancis, it indicates UnimplementedCompanyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CompanyService_ServiceDesc, srv)
}

func _CompanyService_FollowCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).FollowCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_FollowCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).FollowCompany(ctx, req.(*FollowCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_UnfollowCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).UnfollowCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_UnfollowCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).UnfollowCompany(ctx, req.(*UnfollowCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_IsFollowingCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowingCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).IsFollowingCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_IsFollowingCompany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).IsFollowingCompany(ctx, req.(*IsFollowingCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_GetFollowedCompanies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowedCompaniesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).GetFollowedCompanies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_GetFollowedCompanies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).GetFollowedCompanies(ctx, req.(*GetFollowedCompaniesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CompanyService_CheckFollowRequestExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowRequestExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServiceServer).CheckFollowRequestExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CompanyService_CheckFollowRequestExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServiceServer).CheckFollowRequestExists(ctx, req.(*CheckFollowRequestExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CompanyService_ServiceDesc is the grpc.ServiceDesc for CompanyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CompanyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job.CompanyService",
	HandlerType: (*CompanyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowCompany",
			Handler:    _CompanyService_FollowCompany_Handler,
		},
		{
			MethodName: "UnfollowCompany",
			Handler:    _CompanyService_UnfollowCompany_Handler,
		},
		{
			MethodName: "IsFollowingCompany",
			Handler:    _CompanyService_IsFollowingCompany_Handler,
		},
		{
			MethodName: "GetFollowedCompanies",
			Handler:    _CompanyService_GetFollowedCompanies_Handler,
		},
		{
			MethodName: "CheckFollowRequestExists",
			Handler:    _CompanyService_CheckFollowRequestExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connection.proto",
}
